Add androidNative targets + test plugin
Kotlin/kotlinx-atomicfu pull request #206
Opened 2021-10-21 18:09 UTC by natario1

See discussion: https://github.com/Kotlin/kotlinx.atomicfu/issues/122#issuecomment-948865934

To run tests,
- set either $ANDROID_HOME or `multiplatformTesting.androidTools.sdkHome` to the Android SDK directory or, if not installed, to some directory where the plugin can download them
- run `./gradlew atomicfu:runAllAndroidNativeTests`

Testing plugin readme: https://github.com/deepmedia/multiplatform-testing/blob/main/readme.md

2021-12-03 18:42 UTC, natario1 commented
Hi @mvicsokolova , while still hoping that this gets merged soon (I am happy to provide any support)...

Is it OK for you if I publish these artifacts myself in Maven Central, with slightly different coordinates (like `my.company.org.jetbrains.kotlinx:atomicfu` instead of `org.jetbrains.kotlinx:atomicfu`)?

The difference would be that my publication would have Android Native targets, while yours hasn't. Then I can do the same for coroutines and write a simple gradle plugin for dependency substitution for end users. From my understanding, the license allows this, but it would be nice to have your approval, even if informally.

2022-01-19 12:44 UTC, roy-shchory requested changes
What about arm 32 😍

2022-01-19 14:37 UTC, natario1 commented
Arm32 can be added after Kotlin 1.6.20, which contains an important fix for 32bit atomics.

2022-11-02 12:40 UTC, mvicsokolova commented
We postpone the support of android native targets till the guarantees are published for them.
Please see [#122 comment](https://github.com/Kotlin/kotlinx-atomicfu/issues/122#issuecomment-1300306280)

2023-02-21 11:35 UTC, closed without merging