Thread parking for Kotlin/Common
Kotlin/kotlinx-atomicfu pull request #498
Opened 2024-12-19 11:08 UTC by bbrockbernd

Allows to pause and resume thread execution. On native platforms it is based on pthread_cond_wait, on JVM it uses LockSupport.

Threads can be pre unparked (calling unpark before park cancels the parking operation). And thread can be parker with a timeout.

Suspend the current thread by calling:
```Kotlin
Parker.park()
```

Resume a thread by calling:
```Kotlin
Parker.unpark(thread)
```

Get current thread reference by calling:
```Kotlin
val thread = KThread.currentThread()
```

Parking with timout of 500 nano seconds:
```Kotlin
Parker.parkNanos(500)
```

2025-01-16 11:16 UTC, dkhalanskyjb commented on atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/parking/KThread.kt
> +private val localKThread = ThreadLocal<KThread>().also { it.set(KThread()) }
This won't work, you need `ThreadLocal<KThread>.withInitialValue { KThread() }`. The reason: `.also { it.set(KThread()) }` will only be called once, on the thread that is the first to access `localKThread`, whereas the other threads will all have the default value, which is `null`.

2025-01-29 13:14 UTC, ndkoval commented on atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/parking/JvmParkingDelegator.kt
> +// Only for testing purposes
Not only for testing :)

2025-01-29 13:16 UTC, ndkoval commented on atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/parking/JvmParkingDelegator.kt
> +    private val atomicLong: AtomicLong = AtomicLong(0L)
Let's rename it to state, document that these states are "PARKED" and "UNPARKED", and use either `AtomicBoolean` provided AtomicFU or `AtomicIntegerFieldUpdater` if this is easier due to the compilation complexity.

2025-01-29 14:10 UTC, dkhalanskyjb commented on atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/parking/ParkingDelegator.kt
> +internal interface ParkingDelegator {
Unless I'm missing something, on each platform, there is a single implementation of this interface, so extracting it is premature, I feel.

```kotlin
internal expect class ParkingData

internal expect object ParkingDelegator {
    fun createRef(): ParkingData
    fun wait(ref: ParkingData) 
    fun timedWait(ref: ParkingData, nanos: Long)
    fun wake(ref: ParkingData)
    fun destroyRef(ref: ParkingData)
}
```
On the JVM, `internal actual typealias ParkingData = Unit` would achieve the same effect as what we have now.

2025-01-29 14:10 UTC, dkhalanskyjb commented on atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/parking/JvmParkingDelegator.kt
> +        atomicLong.set(0L)
It seems to me like the atomic long here is a protection against spurious wake-ups. Is that it? I don't understand the utility of this safety mechanism. Code using thread parking is often already structured in a way that takes spurious wake-ups into account.

If we do remove the safety mechanism, however, it means that `JvmParkingDelegator` can be stateless and use `Thread` as the reference that's passed around. *That*, in turn, means that there's no need to create a parking delegator instance per thread parker.

2025-01-29 14:14 UTC, dkhalanskyjb commented on atomicfu/src/androidNative64BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        val ts = nativeHeap.alloc<timespec>().ptr
Minor: there's the https://kotlinlang.org/api/core/kotlin-stdlib/kotlinx.cinterop/mem-scoped.html function, which allows creating allocations more structurally.

```kotlin
memScoped {
  val ts = alloc<timespec>()
  clock_gettime(CLOCK_REALTIME.convert(), ts.ptr)
  // ...
  pthread_mutex_unlock(ref.mut)
} // `ts` gets deallocated when this lambda exits
```

2025-01-29 14:42 UTC, dkhalanskyjb commented on atomicfu/src/jsAndWasmSharedMain/kotlin/kotlinx/atomicfu/parking/KThread.kt
> +actual fun currentThreadId(): Long = 1
If we do decide to avoid spurious wake-ups, this implementation is incorrect. But in any case, I think it's also useless to provide it: I'm not sure what anyone using thread synchronization on single-threaded runtimes even expects. As part of the mutex implementation, this particular implementation makes sense, but not for other primitives.

Proposal: create a source set combining JVM and Native (in `kotlinx.coroutines`, we call it `concurrent`), and instead of providing parking in common code, only provide it in `concurrent`. Also, with this source set, it's easier to share tests between `jvmTest` and `nativeTest`: for most of them, it seems possible to put them in `concurrentTest`.

2025-01-29 14:52 UTC, bbrockbernd commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +            rc = pthread_cond_timedwait(ref.cond, ref.mut, ts)
No this should be added, thanks! I will try to run the tests on a 32Bit system.

2025-01-31 13:37 UTC, bbrockbernd commented on atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/parking/JvmParkingDelegator.kt
> +    private val atomicLong: AtomicLong = AtomicLong(0L)
Moved all state to ParkingData similar to native

2025-01-31 13:39 UTC, bbrockbernd commented on atomicfu/src/commonMain/kotlin/kotlinx/atomicfu/parking/ParkingDelegator.kt
> +internal interface ParkingDelegator {
During development I had multiple delegator types, (futex, posix, spinning) and this allowed me to quickly switch between them in tests. But this can now indeed be removed.

Done.

2025-01-31 13:51 UTC, bbrockbernd commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ref.wake.value = true
In the case for native, the calling code should call the destroyRef function to deallocate. There can exists a race condition where:
- thread B (unparker) calls unpark and changes the state to free.
- thread A (parked) spuriously wakes up and since the state changed asumes it was woken up by a wake call. And continues to deallocate ParkingData.
- thread B continues to make the actual wake call, however the reference is destroyed.

So far I have not seen an easy way to solve this, and since parking threads is "expensive" to begin with I don't think it can hurt to leave it here? WDYT?

2025-01-31 13:52 UTC, bbrockbernd commented on atomicfu/src/androidNative64BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        val ts = nativeHeap.alloc<timespec>().ptr
Done

2025-01-31 13:53 UTC, bbrockbernd commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        pthread_cond_destroy(ref.cond)
Done

2025-01-31 13:55 UTC, bbrockbernd commented on atomicfu/src/jsAndWasmSharedMain/kotlin/kotlinx/atomicfu/parking/KThread.kt
> +actual fun currentThreadId(): Long = 1
Good suggestion! Added the sourceSet.
About the tests, spawning threads on Jvm and Native have different API's correct? Or would you suggest creating an expect/actual constructinon for thread manipulation?

2025-01-31 13:57 UTC, bbrockbernd commented on atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/parking/JvmParkingDelegator.kt
> +        atomicLong.set(0L)
I have made the it stateless. However I do still check the spurious wakeups to have similar semantics to the native implementation. Why native needs this check has to do with memory deallocation (which is discussed further there)

2025-01-31 14:11 UTC, dkhalanskyjb commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/parking/ThreadParker.kt
> +                }
Minor, style, subjective:
```suggestion
                STATE_FREE -> if (state.compareAndSet(currentState, STATE_UNPARKED)) return

                STATE_PARKED -> if (state.compareAndSet(currentState, STATE_FREE)) {
                    delegator.wake(atomicRef.value!!)
                    return
                }
```

2025-01-31 14:18 UTC, dkhalanskyjb commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ref.wake.value = true
Ok, I understand now that having this shared mutable state in some form is unavoidable, thanks! Yes, I agree that with the current implementation of `ThreadParker`, this change will lead to a data race. I think this can be avoided by reworking `ThreadParker` to only have one piece of atomic state (`atomic<FREE | UNPARKED | ParkingData>`), but I'm not sure if it would lead to anything useful.

2025-01-31 14:41 UTC, dkhalanskyjb commented on atomicfu/src/jsAndWasmSharedMain/kotlin/kotlinx/atomicfu/parking/KThread.kt
> +actual fun currentThreadId(): Long = 1
We do `expect`/`actual` in our test source sets all the time, and it works without issues: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/concurrent/test/ConcurrentTestUtilities.common.kt.

2025-02-03 08:53 UTC, bbrockbernd commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ref.wake.value = true
Even with a single atomic state it seems difficult to me since we would still have to deallocate the native pthread_cond references. If we let the unparking thread deal with deallocation there exists a different race where the unpark call happens after the state change of park but before the actual `delegator.wait(...)` call.

2025-02-03 10:52 UTC, dkhalanskyjb commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ref.wake.value = true
I think this can be worked around by one more ABA-problem-resilient state (pseudocode below) if we do decide that it's worth doing:

```
fun park() {
  data = ParkingData
  if (state.cas(FREE, data)) {
    data.park()
    state.loop {
      when (it) {
        data -> if (state.cas(it, FREE)) {
          // unparker didn't see the data
          data.free()
          return
        }
        is UnparkAttempt -> if (state.cas(it, FREE)) {
          // we interruped the unparking attempt
          return
        }
        UNPARKED -> if (state.cas(UNPARKED, FREE)) {
          // unparker already left
          data.free()
          return
        }
        else -> error
      }
    }
  } else if (state.cas(UNPARKED, FREE)) {
    return
  } else {
    error
  }
}

fun unpark() {
  myUnparkAttempt = UnparkAttempt()
  state.loop {
    when (it) {
      is ParkingData -> if (state.cas(it, myUnparkAttempt)) {
        // we can attempt unparking. no one will deallocate the data in the meantime.
        it.unpark()
        if (!state.cas(myUnparkAttempt, UNPARKED)) {
          // the parker has already left, it's up to us to free the parking data
          it.free()
        }
        return
      }
      FREE -> if (state.cas(FREE, UNPARKED)) {
        // the parker didn't arrive yet
        return
      }
      UNPARKED -> return // someone already unparked this
      is UnparkAttempt -> return // someone is trying to unpark this
    }
  }
}
```

2025-02-05 10:39 UTC, bbrockbernd commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ref.wake.value = true
Hi, thanks for the suggestion! I have attempted to implement a version on your pseudocode. However, on native there still seems to be a race condition that leads to a thread being in the Unparked state while still waiting. While on JVM we can call `LockSupport.unpark()` before `LockSupport.park()`. On native signaling before waiting, leaves the thead waiting. 
Example:
- Thread P is parking, changes state Free -> data
- Thread U is unparking, observes state data, changes data -> unparkingAttempt, makes native singal call, changes unparkingAttempt -> Unparked
- Thread P makes native wait call.

From now any unpark call will have no effect since it is already in the unparked state.

Why it does work with spurious wakeup protection in native code, is beceause the "wake" state is observed and changed atomically with the signal and wake calls, protected by a `pthread_cond_mutex`.

Additionally, if there are two concurrent unpark calls while a thread is parked. It might result in the end state being "free". While one might expect the 2nd unpark call setting it in the "unparked" state.

Please, let me know if I mis understood something here!

2025-02-05 10:44 UTC, bbrockbernd commented on atomicfu/src/jsAndWasmSharedMain/kotlin/kotlinx/atomicfu/parking/KThread.kt
> +actual fun currentThreadId(): Long = 1
Done

2025-02-05 10:53 UTC, dkhalanskyjb commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ref.wake.value = true
Can we enhance `data.park()` in my snippet so that it also accesses the state after acquiring the lock and [double-checks](https://en.wikipedia.org/wiki/Double-checked_locking) that it hasn't changed?

```kotlin
    data.park(doubleCheckBeforeParking = {
        state.value is ParkingData
    })
```

2025-02-05 11:02 UTC, bbrockbernd commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ref.wake.value = true
Than we would have to protect the state as well on the unparking side, since the state can still change even while holding the lock. Also, this wouldn't solve the concurrent unpark case (not sure if this is a big problem).

2025-02-05 13:07 UTC, bbrockbernd commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ref.wake.value = true
That seems to work. However, there is still the case where two threads unpark the parked thread concurrently and the final state is "free". While I would expect the state to be "unparked". Although, theoretically one could argue that you could observe it like both unpark calls were made before the park call, so not sure if this matters much..

2025-02-06 10:55 UTC, dkhalanskyjb commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/parking/ThreadParker.kt
> +private class UnparkedWhileUnparking(val attempt: Unparking) : ParkingState
What problem does this new state solve? Could you provide a non-linearizable interleaving that this state is protecting against?

2025-02-10 15:17 UTC, dkhalanskyjb commented on atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/parking/KThread.kt
> +actual fun currentThreadId(): Long = Thread.currentThread().id
```suggestion
internal actual fun currentThreadId(): Long = Thread.currentThread().id
```

2025-02-10 15:17 UTC, dkhalanskyjb commented on atomicfu/build.gradle.kts
> +import org.gradle.internal.impldep.org.junit.experimental.categories.Categories.CategoryFilter.exclude
This new import looks unused.

2025-02-10 15:17 UTC, dkhalanskyjb commented on atomicfu/src/androidNative32BitMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_nsec += nanos.toInt() % 1_000_000_000
Here's an incantation that compiles on both 32-bit and 64-bit targets:
```suggestion
        ts.pointed.tv_sec = (ts.pointed.tv_sec + nanos / 1_000_000_000).convert()
        ts.pointed.tv_nsec = (ts.pointed.tv_nsec + nanos % 1_000_000_000).convert()
```
This way, you can remove these custom `androidNative32BitMain`-like source sets and use the source sets provided out of the box like `androidNativeMain` (https://kotlinlang.org/docs/multiplatform-hierarchy.html#see-the-full-hierarchy-template)

2025-02-13 10:58 UTC, dkhalanskyjb requested changes

2025-02-13 10:58 UTC, dkhalanskyjb commented on atomicfu/src/androidNativeMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_nsec += nanos.toInt() % 1_000_000_000
There are a couple of important problems here.

First, an `Int` is about `-2.4 * 10^9 .. 2.4 * 10^9`. If that's nanoseconds, that's just 2.5 seconds: not nearly enough for practical applications of parking. So, converting `nanos` to an `Int` is certainly incorrect.

Second, even if we move `toInt` to outside the division/modulo, the problem is *still* there, just not as pronounced. `2^31` seconds is surely a lot, but `toInt()` doesn't always work like you'd expect. `println(((Long.MAX_VALUE / 3) / 1_000_000_000).toInt())` prints a large *negative* number. So, if someone were to pass `Long.MAX_VALUE / 3` to `timedWait` for some reason, they'd wait for a *negative* number of nanoseconds, which transforms this lock into a spinlock (whether or not we keep the spurious wakeup protection: if we do keep it, the spin lock is in the `Mutex` implementation, and if we don't, the user code will effectively implement the spin lock).

Third: all of this ignores the fact that `tv_sec + something` can *also* overflow, making `tv_sec` negative, again creating a spinlock.

Please ensure that in all cases where arithmetic overflow can happen, the mutex still behaves reasonably.

2025-02-13 10:58 UTC, dkhalanskyjb commented on atomicfu/build.gradle.kts
> +        val linuxMain by getting { dependsOn(nativeUnixLikeMain) }
Minor: these lines can be moved to the `kotlin {` block where `concurrentMain` and `concurrentTest` are created, which makes a couple of lines here redundant and allows this whole `sourceSets` block to be removed.

2025-02-19 15:09 UTC, dkhalanskyjb requested changes

2025-02-19 15:09 UTC, dkhalanskyjb commented on atomicfu/src/nativeUnixLikeMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_sec = min(ts.pointed.tv_sec + nanos / 1_000_000_000, Int.MAX_VALUE.toLong()).convert()
The commit message says:

> Max waiting time is capped at [...] ~68 years.

An important clarification: it's not 68 years from now, it's 68 years from 1970, also known as the https://en.wikipedia.org/wiki/Year_2038_problem .

A solution that I imagine should work with both 32-bit and 64-bit `tv_sec`:

```kotlin
fun tvSecPlusNanos(tvSec: Long, nanos: Long): Long {
    val secondsToAdd = nanos / 1_000_000_000
    val newTvSec = tvSec + secondsToAdd
    // check for a change of sign in the result when the inputs have the same sign
    return if ((tvSec xor newTvSec) < 0 && tvSec >= 0) {
        // a very large Long number, and `Int.MAX_VALUE` when `toInt()/convert<Int>()` is called
        Long.MAX_VALUE - Int.MAX_VALUE - 1
    } else {
        newTvSec
    }
}

ts.pointed.tv_sec = tvSecPlusNanos(tvSec, nanos).convert()
```

I didn't test the function thoroughly, though, and I think it's worth doing, both with preset values (for smoke testing) and some randomly generated `tv_sec` (in the span of `-100..1000` years from now) and arbitrary positive `nanos` that validate the contract of this function.

I imagine the contract is:
* If clamping happens, it's because `tv_sec` is 32-bit, and the value is clamped to `Int.MAX_VALUE`. Nothing else we can do in this scenario, I suppose.
* If clamping doesn't happen, `(newTvSec - tvSec).seconds` should be close to `nanos.seconds`.

2025-02-19 15:46 UTC, bbrockbernd commented on atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/parking/JvmParkingDelegator.kt
> +internal actual class ParkingData(val thread: Thread)
It seems my comment was still "pending". As I tried to say, this solution fails on K1.
```
ACTUAL_WITHOUT_EXPECT] Actual typealias 'ParkingData' has no corresponding expected declaration The following declaration is incompatible because visibility is different:

- internal final expect class ParkingData defined in kotlinx. atomicfu. parking in file ParkingDelegator. kt
```

2025-02-19 15:49 UTC, bbrockbernd commented on atomicfu/src/mingwMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_sec += nanos / 1_000_000_000
On windows `tv_sec` is Long and `tv_nsec` Int

2025-02-19 15:59 UTC, dkhalanskyjb commented on atomicfu/src/mingwMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_sec += nanos / 1_000_000_000
Ok, fair. The max year Windows supports is 30827, according to https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-systemtime, so basically no system can be so misconfigured that an overflow is possible and still function correctly.

2025-02-19 16:29 UTC, dkhalanskyjb commented on atomicfu/src/nativeUnixLikeMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_sec = min(ts.pointed.tv_sec + nanos / 1_000_000_000, Int.MAX_VALUE.toLong()).convert()
Oops. sorry, I just realized this function wasn't any better. I'll think some more.

2025-02-19 17:46 UTC, bbrockbernd commented on atomicfu/src/nativeUnixLikeMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_sec = min(ts.pointed.tv_sec + nanos / 1_000_000_000, Int.MAX_VALUE.toLong()).convert()
For what I understood from the `convert()` function, is that it just calls `toInt()` and takes the least significant 32 bits. (Please correct if wrong). Therefore, I don't think it is possible to have one unified function that can return values larger than Int.Max (in case of 64Bit platform) _and_ maximum Int.max (in case of 32Bit platform).

2025-02-19 18:31 UTC, dkhalanskyjb commented on atomicfu/src/nativeUnixLikeMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_sec = min(ts.pointed.tv_sec + nanos / 1_000_000_000, Int.MAX_VALUE.toLong()).convert()
```kotlin
        ts.pointed.tv_sec = ts.pointed.tv_sec.addNanosToSeconds(nanos)

private fun Long.clampToInt(): Int = coerceIn(Int.MIN_VALUE.toLong(), Int.MAX_VALUE.toLong()).toInt() 
internal fun Int.addNanosToSeconds(nanos: Long): Int = (this + nanos / 1_000_000_000).clampToInt()
internal fun Long.addNanosToSeconds(nanos: Long): Long {
    val sum = this + nanos / 1_000_000_000
    return if ((this xor sum) < 0 && this >= 0) Long.MAX_VALUE else sum
}
```
Seems to do the trick!

2025-02-21 10:56 UTC, dkhalanskyjb commented on atomicfu/src/nativeUnixLikeMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_sec = min(ts.pointed.tv_sec + nanos / 1_000_000_000, Int.MAX_VALUE.toLong()).convert()
A clarification, because it may not be obvious from my message: this if without creating any new source sets, because somehow, Kotlin manages to choose the correct overload for both 32-bit and 64-bit targets when I put this code in the source sets shared by them.

2025-02-21 11:09 UTC, bbrockbernd commented on atomicfu/src/nativeUnixLikeMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_sec = min(ts.pointed.tv_sec + nanos / 1_000_000_000, Int.MAX_VALUE.toLong()).convert()
It'll be pretty far into the future before this overflows right? The maximum added value is `Long.MAX_VALUE / 1_000_000_000` which is around 300 years. And `Long.MAX_VALUE - 300 years` is still billions of years.

```kotlin
if ((this xor sum) < 0 && this >= 0) Long.MAX_VALUE else sum
```

2025-02-21 11:45 UTC, dkhalanskyjb commented on atomicfu/src/nativeUnixLikeMain/kotlin/kotlinx/atomicfu/parking/PosixParkingDelegator.kt
> +        ts.pointed.tv_sec = min(ts.pointed.tv_sec + nanos / 1_000_000_000, Int.MAX_VALUE.toLong()).convert()
Yes.

2025-02-24 11:52 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/parking/TimeArithmeticTests.kt
> +                if (nanos < 0) assertTrue { updatedTime < currentTimeInSeconds && updatedTime >= Int.MIN_VALUE }
```suggestion
                if (nanos > 0) assertTrue { updatedTime > currentTimeInSeconds }
                if (nanos < 0) assertTrue { updatedTime < currentTimeInSeconds }
```
The `updatedTime <= Int.MAX_VALUE` and `updatedTime >= Int.MIN_VALUE` checks are supposed to be always `true` for an `Int`.

2025-02-24 11:52 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/parking/TimeArithmeticTests.kt
> +                if (nanos > 0) assertTrue { updatedTime > currentTimeInSeconds && updatedTime <= Int.MAX_VALUE }
A stronger version of the check: if the value does not clamp, the `(updatedTime - currentTime) == nanos / 1_000_000_000`; if the value clamps, it's because as a `Long` value, it would exceed an `Int`. This describes what we want from `addNanosToSeconds` more precisely. As is, when I write `internal fun Long.addNanosToSeconds(nanos: Long): Long = this + nanos / 2_000_000_000`, for example, no tests fail.

2025-02-24 11:52 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/parking/TimedParkingTest.kt
> +    }
Minor, simplification:
```suggestion
internal class Fut(block: () -> Unit) {
    private val done = atomic(false)
    private val atomicError = atomic<Throwable?>(null)
    private val thread: TestThread = testThread {
        try { block() }
        catch (t: Throwable) {
            atomicError.value = t
            throw t
        }
        finally { done.value = true }
    }

    fun waitThrowing() {
        thread.join()
        throwIfError()
    }

```

2025-04-03 10:42 UTC, dkhalanskyjb requested changes
The implementation is almost ready to go, I believe. Good work! Only some documentation fixes are left, and there's maybe potential to simplify the code.

I haven't looked at the tests yet, though.

2025-04-03 10:42 UTC, dkhalanskyjb commented on atomicfu/build.gradle.kts
> +    applyDefaultHierarchyTemplate()
An approach like https://github.com/Kotlin/kotlinx-datetime/blob/7d2764a54011365b8c6749f3107fa628cd167abc/core/build.gradle.kts#L41-L85 can help avoid manually specifying `concurrentMain` and such.

2025-04-03 10:42 UTC, dkhalanskyjb commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +     * - (Only on JVM) The thread was interrupted
The documentation should mention that the *interrupted status* of the thread is untouched by the method (example: https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#interrupted--). It's also worth spelling out that without clearing the status manually, future attempts to `park` will automatically immediately resume, resulting in a spinlock, as this is quite a pitfall.

2025-04-03 10:42 UTC, dkhalanskyjb commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +     * A [ParkingHandle] can only be pre-unparked once.
Even as someone who knew the logic this documentation is describing, I still doubted myself: "Wait, are `ParkingHandle`s single-use?" I think it's worth explaining the idea more verbosely, like "only one call to `unpark` at a time can be buffered in this manner: even if several `unpark` calls are made before parking happens, the next parking process will not be affected and will suspend as expected", or something like that.

2025-04-03 10:42 UTC, dkhalanskyjb commented on atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +    actual fun parkUntil(deadline: TimeMark) = park(deadline.elapsedNow() * -1)
Question: can the code be simplified if we take `parkUntil` as the fundamental operation and then implement `parkNanos` on top of it? The idea is that POSIX exposes something that's similar to `parkUntil` already, so `waitWithDeadline` may be easier to write than `timedWait`, and `LockSupport.parkUntil` may be somewhat simpler than `LockSupport.parkNanos` (due to the simpler "is it time to exit yet?" check).

2025-04-03 10:42 UTC, dkhalanskyjb commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +     * Returns the [ParkingHandle] that can be used to unpark the current thread.
```suggestion
     * Returns the [ParkingHandle] that can be used to [unpark] the current thread.
```
Easier to follow the breadcrumbs this way.

2025-04-04 08:53 UTC, bbrockbernd commented on atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +    actual fun parkUntil(deadline: TimeMark) = park(deadline.elapsedNow() * -1)
AFAIK, a `TimeMark` is not directly convertible to nanos from epoch. The only way I have found so far is by somehow getting the current time from epoch and subtracting `TimeMark.elapsedNow` (which is converting to duration.)

Additionally, to get current time in nanos from epoch (on native) we either need `kotlinx-datetime` which doesn't seem to be more granular than milliseconds. Or rely on `clock_gettime` from POSIX and convert TimeMark to duration, which is what we currently do.

But I might be missing some api?

2025-04-04 09:34 UTC, dkhalanskyjb commented on atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +    actual fun parkUntil(deadline: TimeMark) = park(deadline.elapsedNow() * -1)
You're right, `TimeMark` does not expose its relationship to absolute time.

`kotlin.time.Instant` (which used to be in `kotlinx-datetime`) does provide nanosecond precision, and in fact, delegates to `clock_gettime`. So, with Kotlin 2.1.20, which introduced `Instant`, it's possible to do this (pseudocode):
```kotlin
fun parkUntil(deadline: TimeMark) {
  val estimatedTargetTime: Instant = Clock.System.now() - deadline.elapsedNow()
  sleepUntil(instant.epochSeconds, instant.nanosecondsOfSecond)
}
```

The problem is, we're not on Kotlin 2.1.20, so we indeed don't have access to `Instant`.

But! This gets me thinking: why do we need an `Instant` at all? It's semantically wrong. In fact, we may have a subtle bug.

See, `CLOCK_REALTIME` (https://man7.org/linux/man-pages/man2/clock_gettime.2.html), `kotlin.time.Instant`, and by default, `pthread_cond_timedwait` (https://docs.oracle.com/cd/E19120-01/open.solaris/816-5137/gfvid/index.html) all have to do with *system time*, that is, what your clock in the corner of the screen says. This clock may get out of sync, and then get back in sync when your system queries the Internet for the up-to-date time.

It seems like the following may happen:
* At 12:13:59, we park for three seconds. We are waiting until 12:14:02.
* One second later, at 12:14:00, we query the Internet and see that our clock is too fast and is into the future by two seconds.
* One second later, it's 12:13:59 again.
* Then, three seconds later, it's finally 12:14:02... but five seconds have passed.

`TimeSource.Monotonic`, though, works with elapsed time, which is what we want.

Proposed fix: https://stackoverflow.com/a/14397906. With this, we don't need to extract epoch time at all.

What do you think?

2025-04-04 11:23 UTC, bbrockbernd commented on atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +    actual fun parkUntil(deadline: TimeMark) = park(deadline.elapsedNow() * -1)
That is quite the edge case! However, the fix proposed relies on `pthread_condattr_setclock` which is not available on darwin. 

Also, I am wondering, is the kotlin `TimeSource.Monotonic` synced to the posix `CLOCK_MONOTONIC`?

2025-04-04 12:14 UTC, dkhalanskyjb commented on atomicfu/src/nativeMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +    actual fun parkUntil(deadline: TimeMark) = park(deadline.elapsedNow() * -1)
> That is quite the edge case!

Indeed, but I'd estimate that every day, someone somewhere encounters this. Having clocks drift by a couple of seconds per day is typical.

> not available on darwin.

Oh, ok. If you also can't think of a way to fix this there, we need to at least document that on Native, the system clock is used and is susceptible to such issues.

> Also, I am wondering, is the kotlin `TimeSource.Monotonic` synced to the posix `CLOCK_MONOTONIC`?

Kotlin/Native delegates to C++'s `std::conditional<high_resolution_clock::is_steady, high_resolution_clock, steady_clock>`. I don't know how our C++ standard library implements those, but it's not necessarily a wrapper around POSIX.

2025-04-08 15:40 UTC, dkhalanskyjb commented on atomicfu/build.gradle.kts
> +            implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.6.2")
This dependency is too heavy to be used here, and it also doesn't seem like it's used.

2025-04-08 15:57 UTC, bbrockbernd commented on atomicfu/build.gradle.kts
> +            implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.6.2")
Oh my bad!

2025-04-14 11:11 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/BarrierTest.kt
> +            println("Barrier test iteration $iteration")
This `println` doesn't seem useful, but will add extra noise in the logs.

2025-04-14 11:14 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/CyclicBarrierTest.kt
> +                        sleepMills(Random.nextLong(100))
In total, these `sleepMillis` affect test execution time considerably. Are they necessary?

2025-04-14 11:18 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/ThreadParkerTest.kt
> +        assertTrue(time.inWholeMilliseconds > 900)
A more reliable (and still less time-consuming) way to test this would be to spin for several thousands of times and see if `park` ever finishes earlier than the corresponding `unpark` (basically, that happens-before is established between the code before `unpark` and the code after `park`).

Also, can't this test be flaky due to spurious wakeups?

2025-04-14 11:30 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/ThreadParkerTest.kt
> +        assertTrue(true)
This line can be safely removed.

2025-04-25 12:21 UTC, dkhalanskyjb requested changes

2025-04-25 12:21 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/TestThread.kt
> +internal fun testThread(doConcurrent: () ->  Unit): TestThread = TestThread { doConcurrent() }
```suggestion
internal fun testThread(doConcurrent: () ->  Unit): TestThread = TestThread(doConcurrent)
```

2025-04-25 12:21 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/ExchangerTest.kt
> +            return waiterPair.second!!
```suggestion
            return waiterPair.second
```

2025-04-25 12:21 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/ThreadParkerTest.kt
> +        assertTrue(done)
Why not use `Fut` here instead of `testThread` and finish the test exactly when the thread stops? I suspect it takes much less than half a second to unpark a thread.

2025-04-25 12:21 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/ThreadParkerTest.kt
> +        assertTrue(done)
This delay seems preventable.

2025-04-25 12:21 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/ThreadParkerTest.kt
> +            sleepMillis(200)
This delay can also be avoided by introducing `@Volatile var unparked = false` that's set to `true` after `unpark`, and here, do `while (!unparked) { sleepMillis(10) }`.

2025-04-25 12:21 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/TimedParkingTest.kt
> +        throw err
Minor, opinionated:
```suggestion
        lastThrowable?.let { throw IllegalStateException("Failed after $times retries").apply { addSuppressed(it) } }
```

2025-04-28 19:56 UTC, fzhinkin commented
There are small formatting issues here and there (like trailing spaces), please run the "Code/Reformat Code" in IJ (you can perform a bulk cleanup by selecting all the necessary files and then running the reformatting).

2025-04-28 21:09 UTC, fzhinkin requested changes
Nicely done! I left a few comments regarding tests and documentation, but overall it looks good.

2025-04-28 21:09 UTC, fzhinkin commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/TimedParkingTest.kt
> +    fun testNanosFirstUnpark400() = retry(3) {
Reliability of these tests worries me. 100ms slack feels huge, but in practice we can accidentally exceed it and got a test failure (and I guess we're already doing that given the test failures on Windows).

For deadline-specific scenarios, I don't think we need to unpark a future from the main thread at all, and we should only verify that it was parked for at least `timeout`-time-units.

For first-unpark-specific scenarios, we can't get away from verifying that the `park` was actually "interrupted" by the `unpark` call, but maybe we can increase the slack to a few minutes, instead of 100ms?

2025-04-29 12:14 UTC, bbrockbernd commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ThreadParker.kt
> +private interface ParkingState
Since a private interface cannot be extended outside the file I thought it wouldn't be necessary but it definitely can't hurt

2025-04-29 12:19 UTC, bbrockbernd commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +     * If [unpark] is called while the corresponding thread is not parked, the next [park] call will return immediately
This path is covered explicitly, in `ThreadParkerTest.unparkPark`. Additionally, the tests in `ThreadParkingStressTest` contain random sleeps before the park and unpark operations and should cover the pre-unpark path regularly.

2025-04-29 12:45 UTC, bbrockbernd commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> + * A call to [ParkingSupport.park] or [ParkingSupport.parkUntil] will suspend the current thread.
I see. My issue with "blocking" is that it could also refer to a busy wait and think it is nice to emphasize that the thread does not use any resources when it is parked. 

How do you like "pause"?

2025-04-29 12:54 UTC, dkhalanskyjb commented on atomicfu/src/androidNativeMain/kotlin/kotlinx/atomicfu/locks/PosixParkingDelegator.kt
> +        callAndVerify(0) { pthread_mutex_unlock(ref.mut) }
This is not an answer to your suggestion but a comment.
That would mean a bug somewhere in `pthread_cond_wait`, as it may not return a non-null value in this situation: https://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_cond_wait.html . `callAndVerify` is an assertion, which should never actually fire; otherwise, the program can not meaningfully recover and we will will to fix the problem in the library.

2025-04-29 14:17 UTC, bbrockbernd commented on atomicfu/src/androidNativeMain/kotlin/kotlinx/atomicfu/locks/PosixParkingDelegator.kt
> +        callAndVerify(0) { pthread_mutex_unlock(ref.mut) }
Good one

2025-04-29 14:23 UTC, bbrockbernd commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/TimedParkingTest.kt
> +    fun testNanosFirstUnpark400() = retry(3) {
Agreed, I tried to fix it with a few retries. But the tests on windows stay unreliable. Thanks for the suggestions!

2025-04-29 15:07 UTC, fzhinkin commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> + * A call to [ParkingSupport.park] or [ParkingSupport.parkUntil] will suspend the current thread.
Sounds good to me

2025-04-30 13:35 UTC, bbrockbernd commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +    fun parkUntil(deadline: TimeMark)
Added them to the timed tests

2025-05-01 12:57 UTC, bbrockbernd commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> + */
What OptIn would you suggest, `ExperimentalMultiplatform` ?

2025-05-12 13:53 UTC, dkhalanskyjb commented on atomicfu/src/concurrentTest/kotlin/kotlinx/atomicfu/locks/CyclicBarrierTest.kt
> +@file:OptIn(ExperimentalThreadBlockingApi::class)
I think the opt-in should be put into `buildSrc/src/main/kotlin/kotlin-base-conventions.gradle.kts` (like `ExperimentalForeignApi` already is). Then, it should be possible to avoid adding `OptIn` everywhere throughout the library.

2025-05-19 18:10 UTC, fzhinkin reviewed
There are a few nits, but otherwise the change looks good.

2025-05-19 18:10 UTC, fzhinkin commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +     * Note: as this function returns a unique [ParkingHandle] for each thread it should not be cached or memoized.
But the example illustrating how to use parking caches (well, publishes, but its hard to tell the difference) the handle:
```
 * // publish my parking handle
 * handleReference.value = ParkingSupport.currentThreadHandle()
```

2025-05-20 13:17 UTC, bbrockbernd commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +    fun park(timeout: Duration)
Currently a negative waiting time already returns immediately. Which is in IMO an expected outcome. 

Additionally, when the users logic calculates the _time left to wait_, the outcome could be negative as some internal deadline might have passed during this calculation. Making negative numbers invalid would force the user to do additional error handling or input validation.

While currently, the user already has to re-evaluate the conditions after every wake-up due to the chance for spurious wake-ups.

So I think it would make use of this API more cumbersome and doesn't give much benefit. 

WDYT?

2025-05-20 15:33 UTC, bbrockbernd commented on atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/locks/JvmParkingDelegator.kt
> +internal actual typealias ParkingData = Thread
Done

2025-05-20 15:37 UTC, bbrockbernd commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +     * Note: as this function returns a unique [ParkingHandle] for each thread it should not be cached or memoized.
I've changed it. Hope it is clearer this way. 

Otherwise, we could maybe remove this note all together since we already mentioned there is a one-to-one correspondance between a thread and the handle?

2025-05-21 12:32 UTC, fzhinkin commented on atomicfu/src/concurrentMain/kotlin/kotlinx/atomicfu/locks/ParkingSupport.kt
> +     * Note: as this function returns a unique [ParkingHandle] for each thread it should not be cached or memoized.
It's much better now, thanks!

And I think it's better to leave the note as it might help some users.

2025-05-21 13:05 UTC, dkhalanskyjb approved these changes
Ok, what next? @ndkoval, do you also want to review this, or can we merge the PR?

2025-05-21 13:22 UTC, ndkoval commented
@dkhalanskyjb please merge the PR.

2025-05-22 16:22 UTC, merged