Apple QoS support via donation
Kotlin/kotlinx-atomicfu pull request #499
Opened 2024-12-19 13:03 UTC by stefanhaustein

Addressing issue #462

2024-12-19 13:43 UTC, stefanhaustein commented
Platform dependencies change diagram: https://docs.google.com/presentation/d/1JtQ5GsjDmhtPKCYkzxPwRp-fD58NiKMw4nIi85_M7kg/edit?usp=sharing

2025-01-28 18:20 UTC, qwwdfsad requested changes
Great job!

I have a few essential comments on Apple-related implementation, and it's good to go. To avoid extra-round trips please take a look at new warnings produced by `./gradlew build`.

I would also kindly ask (but I'll accept the CR without it) to align non-apple `SynchronizedObject` with the current implementation as well -- you can copy-paste it but remove QoS mentions, or you can make this code part of `nativeMain` with `expect` `DonatingMonitor`, whatever is easier. Having two **different** implementations going to be real PITA here

2025-01-28 18:20 UTC, qwwdfsad commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +    private val waiters: AtomicInt = atomic(0)
Calling this `waiters` is semantically confusing: if there exists only a single thread that locks the lock, `waiters` fluctuates between 0 and 1.

Have you considered renaming it? (e.g. `threadsOnLock` or something like that) and dropping a comment?

2025-01-28 18:20 UTC, qwwdfsad commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +    private val owner: AtomicLong = atomic(NO_OWNER)
Please consider naming it `ownerThreadId` -- generally `owner` means `Any` in our lingua

2025-01-28 18:20 UTC, qwwdfsad commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +                    val lockOwnerQosClass = alloc<UIntVar>()
It's pretty much likely that this allocation will be happen on each contention and it's a real `malloc`.

Is it possible to extract this `alloc` into `DonatingMonitor` level and free it within cleaner?

2025-01-28 18:20 UTC, qwwdfsad commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +                        qosOverride = pthread_override_qos_class_start_np(lockOwner.toCPointer(), qos_class_self(), 0)
We can reuse `ourQosClass` here instead of calling `qos_class_self`, can't we?

2025-01-29 14:33 UTC, bbrockbernd commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +        val nativeMutex = mutexPool.allocate()
Since mutexPool.allocate() is only called once and therefore only a single node is used. I believe we can get rid of MutexPool all together. By replacing this line for `val nativeMutex = NativeMutexNode()`. And replacing the cleaner with `val cleaner = createCleaner(nativeMutex) { it.dispose() }`.

2025-01-29 14:33 UTC, bbrockbernd commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +                        qosOverride = pthread_override_qos_class_start_np(lockOwner.toCPointer(), qos_class_self(), 0)
I think there is a race condition possible here:
Let’s say we have thread 1 and 2 with low priority and thread 3 with high priority. 

Thread 1 is holding the lock and doing work, thread 2 is suspended and waiting for the lock to be released. There is no qos override since 1 and 2 have equal priority. 

Now, if thread 3 (high priority) tries to acquire the lock it would reach this point (line 173) in the code (please correct me if I’m wrong). If in the meantime thread 1 releases the lock and thread 2 therefore acquires it, then the `lockOwner` reference is outdated and we would override priority from thread 1 and not the new lock holder thread 2.

2025-01-29 16:08 UTC, stefanhaustein commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +        private const val NO_OWNER = 0L
Done

2025-01-29 16:08 UTC, stefanhaustein commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +            val ourQosClass = qos_class_self() as UInt
Removed

2025-01-29 16:08 UTC, stefanhaustein commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +    private val waiters: AtomicInt = atomic(0)
Renamed as suggested

2025-01-29 16:09 UTC, stefanhaustein commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +    private val owner: AtomicLong = atomic(NO_OWNER)
renamed as suggested

2025-01-29 16:10 UTC, stefanhaustein commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +                    val lockOwnerQosClass = alloc<UIntVar>()
Shouldn't this just be a stack allocation (via memScoped)? It's just used short-lived for getting the values back, perhaps I am holding it wrong?

2025-01-29 16:10 UTC, stefanhaustein commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +                        qosOverride = pthread_override_qos_class_start_np(lockOwner.toCPointer(), qos_class_self(), 0)
Done

2025-01-29 16:13 UTC, stefanhaustein commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +        val nativeMutex = mutexPool.allocate()
While reducing the number of classes and objects by one, I think this might reduce readability. I don't have a strong option either way, but I'd prefer to keep the pool aligned with the implemenations for the other platforms, at least until we have merged them in a followup?

2025-01-29 16:14 UTC, stefanhaustein commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +                        qosOverride = pthread_override_qos_class_start_np(lockOwner.toCPointer(), qos_class_self(), 0)
Thread 2 shouldn't be able to acquire the mutex in waitForUnlockAndLock while Thread 3 holds it on line 173?

2025-01-29 16:21 UTC, stefanhaustein commented
> I have a few essential comments on Apple-related implementation, and it's good to go. To avoid extra-round trips please take a look at new warnings produced by `./gradlew build`.

I checked the IDE for warnings and fixed the threadlocal package. Not sure about the redundant "public" modifiers? For some bits (forked from the compose implementation) I was not sure to which extent they were outdated or intended for some reason. Unfortunately, `gradlew build` is full of gazillions of expect / actual warnins. I did a quick search for the flag in combination with gradlew but did not see anything obvious....

> I would also kindly ask (but I'll accept the CR without it) to align non-apple `SynchronizedObject` with the current implementation as well -- you can copy-paste it but remove QoS mentions, or you can make this code part of `nativeMain` with `expect` `DonatingMonitor`, whatever is easier. Having two **different** implementations going to be real PITA here

SGTM but let me do this in a followup.

2025-01-29 17:14 UTC, bbrockbernd commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +                        qosOverride = pthread_override_qos_class_start_np(lockOwner.toCPointer(), qos_class_self(), 0)
Ah I see, donation happens between pthread_mutex_lock and pthread_mutex_wait. My bad!

2025-01-29 17:17 UTC, bbrockbernd commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +        val nativeMutex = mutexPool.allocate()
I would argue that having unnecessary code decreases readability, but as you said this will probably be resolved when the apple and non-apple implementations are unified.

2025-02-04 11:17 UTC, stefanhaustein commented
Does this make sense? Not sure why the requested change is still highlighted -- it should be addressed in the updated branch....

2025-02-06 19:01 UTC, qwwdfsad commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +                    val lockOwnerQosClass = alloc<UIntVar>()
`memScoped` is still a real allocation, we have no stack allocation in K/N AFAIR

2025-02-06 19:08 UTC, qwwdfsad commented
I've run the remote build. In the meantime, PTAL at the malloc commentary

2025-02-06 19:09 UTC, qwwdfsad reviewed
.

2025-02-07 11:18 UTC, stefanhaustein commented on atomicfu/src/appleMain/kotlin/kotlinx/atomicfu/locks/Synchronized.kt
> +                    val lockOwnerQosClass = alloc<UIntVar>()
Done

2025-02-07 11:19 UTC, stefanhaustein commented
> I've run the remote build. In the meantime, PTAL at the malloc commentary

Done.

2025-02-11 18:02 UTC, qwwdfsad commented
Functional tests passed, now I'm on benchmarks. Almost there :)

2025-02-12 16:20 UTC, qwwdfsad approved these changes
All good, thanks!

Could you please consider the follow-up that removed the duplicate implementation with a different mechanism (non-apple locks)?

2025-02-12 16:20 UTC, merged